WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Current dir exists, do you want to remove and refresh it?
Current dir exists, do you want to remove and refresh it?
Dir Not removed !
Loading model
Use Bidirectional Add Fusion
res3_0_branch1_w: (512, 320, 1, 1, 1) => s3.pathway0_res0.branch1.weight: (512, 256, 1, 1, 1)
res5_0_branch2a_w: (512, 1280, 3, 1, 1) => s5.pathway0_res0.branch2.a.weight: (512, 1024, 3, 1, 1)
res4_0_branch2a_w: (256, 640, 3, 1, 1) => s4.pathway0_res0.branch2.a.weight: (256, 512, 3, 1, 1)
res2_0_branch2a_w: (64, 80, 1, 1, 1) => s2.pathway0_res0.branch2.a.weight: (64, 64, 1, 1, 1)
res3_0_branch2a_w: (128, 320, 1, 1, 1) => s3.pathway0_res0.branch2.a.weight: (128, 256, 1, 1, 1)
res2_0_branch1_w: (256, 80, 1, 1, 1) => s2.pathway0_res0.branch1.weight: (256, 64, 1, 1, 1)
res4_0_branch1_w: (1024, 640, 1, 1, 1) => s4.pathway0_res0.branch1.weight: (1024, 512, 1, 1, 1)
!! pred_b: can not be converted, got head.projection.bias
!! pred_w: can not be converted, got head.projection.weight
res5_0_branch1_w: (2048, 1280, 1, 1, 1) => s5.pathway0_res0.branch1.weight: (2048, 1024, 1, 1, 1)
Not loaded {'s1_fuse.weight_s', 's1_fuse.weight_f', 's2_fuse.bn2.running_var', 's1_fuse.conv_f2s.weight', 's2_fuse.bn2.running_mean', 's4_fuse.weight_f', 's2_fuse.conv_s2f.weight', 's4_fuse.bn2.weight', 's1_fuse.bn2.running_mean', 's2_fuse.weight_s', 's1_fuse.bn2.running_var', 's4_fuse.conv_f2s.weight', 's3_fuse.weight_s', 's4_fuse.bn2.bias', 's4_fuse.conv_s2f.weight', 's3_fuse.bn2.running_mean', 's2_fuse.bn2.weight', 's2_fuse.conv_f2s.weight', 's3_fuse.conv_f2s.weight', 's3_fuse.weight_f', 's2_fuse.bn2.bias', 's1_fuse.bn2.bias', 's4_fuse.bn2.running_mean', 's1_fuse.bn2.weight', 's1_fuse.conv_s2f.weight', 's3_fuse.bn2.weight', 's3_fuse.bn2.bias', 's4_fuse.bn2.running_var', 's3_fuse.bn2.running_var', 's3_fuse.conv_s2f.weight', 's2_fuse.weight_f', 's4_fuse.weight_s'}
Dir Not removed !
Loading model
Use Bidirectional Add Fusion
res3_0_branch1_w: (512, 320, 1, 1, 1) => s3.pathway0_res0.branch1.weight: (512, 256, 1, 1, 1)
res5_0_branch2a_w: (512, 1280, 3, 1, 1) => s5.pathway0_res0.branch2.a.weight: (512, 1024, 3, 1, 1)
res4_0_branch2a_w: (256, 640, 3, 1, 1) => s4.pathway0_res0.branch2.a.weight: (256, 512, 3, 1, 1)
res2_0_branch2a_w: (64, 80, 1, 1, 1) => s2.pathway0_res0.branch2.a.weight: (64, 64, 1, 1, 1)
res3_0_branch2a_w: (128, 320, 1, 1, 1) => s3.pathway0_res0.branch2.a.weight: (128, 256, 1, 1, 1)
res2_0_branch1_w: (256, 80, 1, 1, 1) => s2.pathway0_res0.branch1.weight: (256, 64, 1, 1, 1)
res4_0_branch1_w: (1024, 640, 1, 1, 1) => s4.pathway0_res0.branch1.weight: (1024, 512, 1, 1, 1)
!! pred_b: can not be converted, got head.projection.bias
!! pred_w: can not be converted, got head.projection.weight
res5_0_branch1_w: (2048, 1280, 1, 1, 1) => s5.pathway0_res0.branch1.weight: (2048, 1024, 1, 1, 1)
Not loaded {'s3_fuse.weight_f', 's2_fuse.bn2.running_mean', 's3_fuse.conv_f2s.weight', 's2_fuse.bn2.bias', 's4_fuse.bn2.running_var', 's1_fuse.weight_s', 's4_fuse.conv_s2f.weight', 's4_fuse.bn2.weight', 's1_fuse.bn2.running_var', 's1_fuse.weight_f', 's3_fuse.bn2.running_var', 's2_fuse.weight_f', 's4_fuse.bn2.bias', 's4_fuse.conv_f2s.weight', 's4_fuse.bn2.running_mean', 's4_fuse.weight_s', 's2_fuse.conv_s2f.weight', 's1_fuse.conv_f2s.weight', 's3_fuse.bn2.weight', 's4_fuse.weight_f', 's2_fuse.bn2.weight', 's3_fuse.bn2.running_mean', 's1_fuse.bn2.bias', 's3_fuse.conv_s2f.weight', 's3_fuse.weight_s', 's2_fuse.weight_s', 's2_fuse.conv_f2s.weight', 's2_fuse.bn2.running_var', 's1_fuse.conv_s2f.weight', 's1_fuse.bn2.weight', 's3_fuse.bn2.bias', 's1_fuse.bn2.running_mean'}
Traceback (most recent call last):
  File "main.py", line 315, in <module>
Traceback (most recent call last):
  File "main.py", line 315, in <module>
    processor = Processor(args)
  File "main.py", line 66, in __init__
    processor = Processor(args)
  File "main.py", line 66, in __init__
    self.model, self.optimizer = self.loading()
  File "main.py", line 163, in loading
        self.kernel_sizes = model.conv1d.kernel_sizeself.model, self.optimizer = self.loading()

  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
  File "main.py", line 163, in loading
    self.kernel_sizes = model.conv1d.kernel_size
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
        raise AttributeError("'{}' object has no attribute '{}'".format(raise AttributeError("'{}' object has no attribute '{}'".format(

AttributeErrorAttributeError: : 'DistributedDataParallel' object has no attribute 'conv1d''DistributedDataParallel' object has no attribute 'conv1d'

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2871908) of binary: /shared/home/xvoice/anaconda3/envs/signL/bin/python
Traceback (most recent call last):
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/shared/home/xvoice/anaconda3/envs/signL/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-07-16_19:21:04
  host      : a100-n3-eno2
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2871909)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-16_19:21:04
  host      : a100-n3-eno2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2871908)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
